name: 🐛 Bug Report
description: Report a bug to help us improve Bitcoin Enterprise Suite
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.
        
        **Before submitting**: Please search existing issues to avoid duplicates.
        
  - type: dropdown
    id: library
    attributes:
      label: Affected Library
      description: Which library is affected by this bug?
      options:
        - BiSCOL (Bitcoin Smart Contract Orchestration)
        - CCI-SAT (Cross-Chain Interoperability)
        - AICRM-SDK (AI-Driven Compliance & Risk Management)
        - IMO-EO (Mining Operations & Energy Optimization)
        - Multiple Libraries
        - Documentation
        - Build System / CI/CD
        - Other/Unknown
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Import the library with `use biscol::SmartContract;`
        2. Call the function with parameters '...'
        3. Observe the error or unexpected behavior
        4. See error message: "..."
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen instead
      placeholder: Describe the expected behavior...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
      placeholder: Describe what actually happened, including full error messages...
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Please provide your environment information
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 14.0, Windows 11]
        - Rust version: [e.g. 1.70.0] (run `rustc --version`)
        - Library version: [e.g. 0.1.0] (check your Cargo.toml)
        - Bitcoin network: [e.g. mainnet, testnet, regtest]
      render: markdown
    validations:
      required: true
      
  - type: textarea
    id: code
    attributes:
      label: Minimal Code Example
      description: If applicable, provide a minimal code example that reproduces the issue
      placeholder: |
        ```rust
        use biscol::SmartContract;
        
        fn main() {
            // Your code that demonstrates the issue
        }
        ```
      render: rust
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      placeholder: |
        Include any error messages, stack traces, or debug output.
        Set RUST_LOG=debug for more detailed logs.
      render: shell
      
  - type: dropdown
    id: impact
    attributes:
      label: Impact Level
      description: How does this bug affect your work?
      options:
        - Critical (blocking production use)
        - High (significant impact on development)
        - Medium (workaround available)
        - Low (minor inconvenience)
    validations:
      required: true
      
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: I have provided all requested information
          required: true
        - label: I have tested with the latest version
          required: true
        - label: This is a bug report, not a feature request
          required: true