name: ✨ Feature Request
description: Suggest an idea for Bitcoin Enterprise Suite
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.
        
        **Before submitting**: Please search existing issues and discussions to avoid duplicates.
        
  - type: dropdown
    id: library
    attributes:
      label: Target Library
      description: Which library should this feature be added to?
      options:
        - BiSCOL (Bitcoin Smart Contract Orchestration)
        - CCI-SAT (Cross-Chain Interoperability)
        - AICRM-SDK (AI-Driven Compliance & Risk Management)
        - IMO-EO (Mining Operations & Energy Optimization)
        - New Library (describe in details)
        - Documentation
        - Infrastructure / CI/CD
        - Multiple Libraries
        - Not sure / Need guidance
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: |
        Describe the problem or limitation you're experiencing...
        
        For example:
        - "Currently, there's no way to..."
        - "It's difficult to achieve... because..."
        - "Users often struggle with..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        Describe how you'd like this feature to work...
        
        Include details about:
        - API design (if applicable)
        - User interface changes
        - Configuration options
        - Integration points
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What alternative solutions have you considered?
      placeholder: |
        Describe any alternative approaches you've thought about...
        
        This could include:
        - Workarounds you're currently using
        - Different API designs
        - Third-party solutions
        - Manual processes
      
  - type: textarea
    id: use_case
    attributes:
      label: Use Case Example
      description: Provide a concrete example of how this feature would be used
      placeholder: |
        ```rust
        // Example of how the proposed feature might be used
        use biscol::NewFeature;
        
        fn main() {
            let feature = NewFeature::new();
            // Show how it would work...
        }
        ```
      render: rust
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you and your work?
      options:
        - Critical (blocking current project)
        - High (would significantly improve workflow)
        - Medium (nice to have improvement)
        - Low (minor enhancement)
    validations:
      required: true
      
  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small API addition, minimal changes)
        - Medium (moderate changes, some new components)
        - Complex (significant architectural changes)
        - Very Complex (major redesign or new subsystem)
        - Not sure / Need expert assessment
        
  - type: textarea
    id: impact
    attributes:
      label: Expected Impact
      description: Who would benefit from this feature and how?
      placeholder: |
        Describe the expected impact:
        - Who would use this feature?
        - How would it improve their experience?
        - What new capabilities would it enable?
        - Are there performance or security benefits?
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information, screenshots, links, or references
      placeholder: |
        Include any additional context such as:
        - Links to relevant documentation or specifications
        - Screenshots or mockups
        - References to similar features in other projects
        - Research or benchmarks supporting the feature
        
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'd be willing to submit a PR for this feature
          required: false
        - label: I'd be willing to help with testing
          required: false
        - label: I'd be willing to help with documentation
          required: false
        - label: I can provide domain expertise/consultation
          required: false
          
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar requests
          required: true
        - label: I have provided a clear problem statement and solution
          required: true
        - label: This is a feature request, not a bug report
          required: true
        - label: I understand this may require community discussion before implementation
          required: true